In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv(r"C:\Users\asus\INeuron\winequalityN.csv")

In [3]:
data.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [5]:
total=data.isnull().sum().sort_values(ascending=False)
per=data.isnull().sum()/data.isnull().count().sort_values(ascending=False)
pd.concat([total,per],keys=['Missing_values','Percentage'],axis=1)

                      Missing_values  Percentage
fixed acidity                     10    0.001539
pH                                 9    0.001385
volatile acidity                   8    0.001231
sulphates                          4    0.000616
citric acid                        3    0.000462
chlorides                          2    0.000308
residual sugar                     2    0.000308
quality                            0    0.000000
alcohol                            0    0.000000
density                            0    0.000000
total sulfur dioxide               0    0.000000
free sulfur dioxide                0    0.000000
type                               0    0.000000

In [8]:
total=data.isnull().sum().sort_values(ascending=False)
per=data.dtypes.sort_values(ascending=False)
pd.concat([total,per],keys=['Missing_values','Percentage'],axis=1)

                      Missing_values Percentage
fixed acidity                     10    float64
pH                                 9    float64
volatile acidity                   8    float64
sulphates                          4    float64
citric acid                        3    float64
chlorides                          2    float64
residual sugar                     2    float64
quality                            0      int64
alcohol                            0    float64
density                            0    float64
total sulfur dioxide               0    float64
free sulfur dioxide                0    float64
type                               0     object

In [7]:
# handling with missing values